version: '3'
services:
  elastic:
    image: elasticsearch:7.4.2
    ports:
      - 9200:9200
      - 9300:9300
    environment: 
      - "discovery.type=single-node" 
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
      - "http.cors.allow-credentials=true"